### ISSUE TITLE
mem0.get_all() failed: 'tuple' object has no attribute 'id'

### ISSUE THREAD

**Issue by ArnabhS** [mem0ai/mem0#3419]
### 🐛 Describe the bug

In Mem0 Open source when configured with MongoDB database. The get_all() function is returning an error. 
mem0.get_all() failed: 'tuple' object has no attribute 'id'.

**Comment by parshvadaftari** [comment]
@ArnabhS what's the version which you're using and can you share me code snippet??

**Comment by parshvadaftari** [comment]
Hey @ArnabhS this issue was fixed with the latest releases, closing the issue. Thanks again for reaching out!

**Comment by aesher9o1** [comment]
hi @parshvadaftari i am still facing this issue for MongoDB  #3596  fixes it

**Comment by parshvadaftari** [comment]
Hey @aesher9o1 thank you for pointing it out, will review the solution.
